### ISSUE TITLE
'save' doesn't dismiss controller

### ISSUE THREAD

**Issue by coreymalek** [pavelpark/Objective-C#7]
More of a UX bug so not a huge deal, but still something to think about:

![screen shot 2017-04-20 at 12 05 24 pm](https://cloud.githubusercontent.com/assets/18276076/25248110/e1b7eb0a-25c1-11e7-8357-b8811ce1fab1.png)

When you click 'save' on the 'new employee' view controller, a message pops up in the console that the employee has been saved and when you go to the employee list, the added employee shows up. So that's good BUT the view controller does not dismiss when the new employee has been saved, only when you click the 'cancel' button. I would consider a couple of other options to make it run a little smoother .. 

You could add an 'X' at the top corner of the view to dismiss the view controller instead of a literal 'cancel' button. And then add an alert when you click 'save' that shows the user that the new employee has been saved. 

OR

Have the view dismiss each time a new employee has been saved as well as when the user clicks 'cancel'. 

Again, this is just a matter of design choice. But it's important to remember that you're going to be creating apps with the user's experience in mind, not just something that works.

**Comment by pavelpark** [comment]
I have it that was so that if the manager wants to add a lot of employees it doesn't bring him to the list every time and so that he can keep on adding them and then when he wants to he can go back to the list and it will display all the employees that he added.
